### ISSUE TITLE
Folder utils doesn't contain image_preprocessing.py

### ISSUE THREAD

**Issue by xiangshb** [agaldran/cost_sensitive_loss_classification#1]
when I run the script **prepare_test_data.py**

this line 18 occurs error
from utils.image_preprocessing import **correct_illumination**

can you please provide the script **image_preprocessing.py** which include the function correct_illumination?

thanks very much.

**Comment by agaldran** [comment]
Hi!

I have added that missing file. However, if I remember well, I did not do any pre-processing (beyond cropping) in this project.

Cheers,

Adrian

**Comment by xiangshb** [comment]
> Hi!
> 
> I have added that missing file. However, if I remember well, I did not do any pre-processing (beyond cropping) in this project.
> 
> Cheers,
> 
> Adrian

Hi, Thanks for your help.
