### ISSUE TITLE
Readme invalid cmd snippet (labmd -> lambd)

### ISSUE THREAD

**Issue by Ahinterd** [agaldran/cost_sensitive_loss_classification#2]
`python train.py --csv_train train.csv --model_name resnext50 --base_loss gls --labmd 10 --exp 2 --save_path gls_reg_1e2_resnext50_exp2`

Should be:
`python train.py --csv_train train.csv --model_name resnext50 --base_loss gls --lambd 10 --exp 2 --save_path gls_reg_1e2_resnext50_exp2`

**Comment by agaldran** [comment]
Right, thanks @Ahinterd , it's fixed now I think.
